import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import Navigation from './components/Navigation';
import { AppProvider } from './context/AppContext';
import Cart from './components/Cart';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Giuseppe's Pizzeria Collective",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <Head>
                <title>{metadata.title}</title>
                <link rel="icon" href="/favicon.ico" />
                <meta charSet="utf-8" />
                <meta name="viewport" content="initial-scale=1.0, width=device-width" />
            </Head>
            <body className={inter.className}>
                <AppProvider>
                    <Navigation />
                    <Cart />
                    <div className="container mx-auto px-4">
                        {children}
                    </div>
                </AppProvider>
            </body>
        </html>
    );
}
